### ISSUE TITLE
再提一个问题

### ISSUE THREAD

**Issue by wangyouqi** [Xposed-Modules-Repo/com.kgg.hlddz#4]
在7.0.155的版本里无效，
因为只有7.0.155的版本以下才有三日任务，如果能去掉强制更新验证就更好了

加油作者

**Comment by 156209258y** [comment]
欢乐斗地主就发现QQ小程序有广告   商场里面的欢乐斗地主都没有刚刚    疑惑😦   这个模块怎么用？

**Comment by KongGuoguang** [comment]
> 欢乐斗地主就发现QQ小程序有广告 商场里面的欢乐斗地主都没有刚刚 疑惑😦 这个模块怎么用？

免费抽奖、幸运转盘这些领取奖励的功能需要看十几秒广告，这个模块能让这些广告自动跳过
