### ISSUE TITLE
斗地主新版本，导致跳广告失效

### ISSUE THREAD

**Issue by s37572** [Xposed-Modules-Repo/com.kgg.hlddz#5]
更新至斗地主8.018.138版本，模块跳广告就失效了！

**Comment by KongGuoguang** [comment]
我手机上就是8.018.138这个版本，亲测还能用

登录界面顶部显示版本号：8.018.138.7954   资源号：8.018.138.9426

你看下你的是不是这个版本

**Comment by s37572** [comment]
我的登录界面 版本号：8.018.138.7954 资源号：8.018.138.9426&nbsp;
&nbsp;刚才测试了一下。回退到1.0.2 即可正常跳广告！
测试手机：小米13 pro
系统：安卓13
MIUI版本：MIUI14.0.10




隔壹迣嬡沵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xposed-Modules-Repo/com.kgg.hlddz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 中午12:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xposed-Modules-Repo/com.kgg.hlddz] 斗地主新版本，导致跳广告失效 (Issue #5)





 
我手机上就是8.018.138这个版本，亲测还能用
 
登录界面顶部显示版本号：8.018.138.7954   资源号：8.018.138.9426
 
你看下你的是不是这个版本
